# **Numpy provides special data structures , functions and other tools for Numerical computing in python**

In [ ]:
import numpy as np

Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.

yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity

In [ ]:
w1,w2,w3 = 0.3 , 0.2 , 0.5

In [ ]:
w1,w2,w3 = 0.3 , 0.2 , 0.5
west_temperature = 73
west_rainfall = 67
west_humidity = 43

west_apple_yield = west_temperature * w1 + west_rainfall * w2 + west_rainfall * w3
print(west_apple_yield)

To make it slightly easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector, i.e., a list of numbers.

In [ ]:
west = [45 , 78 , 69]
east = [85 , 65 , 52]
north = [86 , 53 , 35]
south = [42 , 98 , 20]

weights = [w1 , w2, w3]

In [ ]:
def crop_yield(region ,weights):
    result = 0
    for a , b in zip(region, weights):
        result = result + a*b
    return result

crop_yield(east ,weights )

In [ ]:
crop_yield(north ,weights)

**The calculation performed by the crop_yield (element-wise multiplication of two vectors and taking a sum of the results) is also called the dot product.**

In [ ]:
import numpy as np
west = np.array([45 , 85  ,56])
west

In [ ]:
weights = np.array([0.3 ,0.5 ,0.2])
weights

In [ ]:
(west * weights).sum()

Create an array of 10 random integers

In [ ]:
import numpy as np
a = np.random.randint(1,100,10)
a

In [ ]:
#create an array of elements from 10-20
import numpy as np
b = np.arange(10,21)
b

In [ ]:
#create an array of elements of 5 which is repeated 10 times

#np.ones is used the to create the array with value 1 only
import numpy as np
c = np.ones(10)*5
c

In [ ]:
#create a one dimensional array and convert it into 3d array


#reshape function is used to convert the dimension of the array
import numpy as np
d = np.arange(1,10).reshape(3,3)
d

In [ ]:
#create an array and convert all the even elements with 0
import numpy as np
e = np.arange(1,11)
e[e%2==0]=0
e

In [ ]:
#rand is a function which is used to generate values only between 0 and 1
import numpy as np
a = np.random.rand(9).reshape(3,3)
a

In [ ]:
# perform the following slicing
#a1[1:,1:3] first one is for row second one is for column slicing
import numpy as np
a1 = np.arange(1,17).reshape(4,4)
a2 = a1[1:,1:3]
a2

# **NumPy hstack() function in Python is used to stack or concatenate arrays in sequence horizontally (column-wise)**

In [ ]:
#Concatenate 2d array horizontally and vertically 
import numpy as np  
a1 = np.arange(1,10).reshape(3,3)
a2 =np.arange(10 ,19).reshape(3,3)
np.hstack((a1,a2))

# **numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.**

In [ ]:
#concatenate 2d array vertically 
import numpy as np
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(10 ,19).reshape(3,3)
np.vstack((a1,a2))

In [ ]:
#Print the numpy version and the configuration 
import numpy as np
np.show_config()

In [ ]:
#create a null vector of size 10
import numpy as np
a1 = np.zeros(10)
a1

In [ ]:
#craete a null vector of size 10 but the 5th value is 4
import numpy as np
a1=np.zeros(10)
a1[4] = 4
a1

In [ ]:
#create a vector with values ranging from 10 to 49
import numpy as np
a1 = np.arange(10,50)
a1

In [ ]:
#reverse a vector
import numpy as np
a1 = np.arange(1,20)
a1=a1[::-1]
a1

# **np.Nonzero function** 
Return the indices of the elements that are non-zero.

In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
a = np.nonzero([1,2,0,0,4,0])
a

# Np.eye function
Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
#Create a 3x3 identity matrix
# 3 is the number of rows
a = np.eye(3)
a

In [ ]:
#Create a 3x3x3 array with random values
a = np.random.random((3,3,3))
a

In [ ]:
 #Create a 10x10 array with random values and find the minimum and maximum values
a = np.random.random((10,10))
amin , amax = a.min() ,a.max()
print(amin , amax)

In [ ]:
#Create a random vector of size 30 and find the mean value 
a = np.random.random(30)
a
b = a.mean()
b

In [ ]:
#craete a random vector of size 10 and sort it 
a = np.random.random(10)
a.sort()
a

In [ ]:
#ndim function will give you the dimension of the array 
#a.size function will give the total number of elements in an array 
#a.shape function will give the dimension of the array 
a = np.array([[1,2],[3,4],[5,6]])
a.ndim
a.size
a.shape

In [ ]:
#dtype is used to convert the datatype and tell the datatype

#how to change the datatype of an array
a = np.array([1,2,3] , dtype = np.float64)
a.dtype

In [ ]:
#convert the array into complex datatype
a = np.array([1 , 2 , 3 ] ,dtype = np.complex128)
a.dtype

In [ ]:
#add all the column of the matrix
a = np.arange(1,10).reshape(3,3)
a

In [ ]:
a.sum(axis = 0)

In [ ]:
#add all the rows of the matrix
a.sum(axis = 1)

In [ ]:
a1 = np.arange(1,7).reshape(3,2)
a1

In [ ]:
#dot function is used 
a1 = np.array([1,2])
a2 = np.array([2,4])
l = np.dot(a1,a2)
l

# Boolean Indexing

In [ ]:
#Boolean indexing checks wether the condition is true or false
a = np.array([1 ,4 ,5 ,6])
a==4

In [ ]:
#extract the array np.array([3,4,6,10,24,89,45,43,46,99,100])  which is not divisible by 3
a = np.array([3,4,6,10,24,89,45,43,46,99,100]) 
div3 = a[a%3!=0]
div3

In [ ]:
#extract the array np.array([3,4,6,10,24,89,45,43,46,99,100])  which is  divisible by 5
a = np.array([3,4,6,10,24,89,45,43,46,99,100]) 
div5 = a[a%5==0]
div5

In [ ]:
#extract the array np.array([3,4,6,10,24,89,45,43,46,99,100])  which is  divisible by 3 and 5

c=(a[(a%3==0) & (a%5==0)])
c

In [ ]:
#Iterate through rows
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
#for row in a:
    #print (row)
    
for cell in a.flat:
    print(cell)

In [ ]:
a = np.arange(12).reshape(3,4)
b = a>4
b

In [ ]:
a[b]